### ISSUE TITLE
This isn't an issue

### ISSUE THREAD

**Issue by metonym** [feltcoop/why-svelte#2]
I just want to commend how well structured and articulated your arguments are.

I predict that this repo will become a "founding document" for Svelte. I'll certainly be referring my colleagues/collaborators to this when recommending Svelte.

**Comment by ryanatkn** [comment]
Thank you so much, that means a lot. I'm glad what started as a document directed at my friend can help others open a conversation with their coworkers. The innovation happening all across the JavaScript community has been inspiring to follow.
